[build]
  publish = "dist"
  command = "rm -rf node_modules package-lock.json && npm cache clean --force && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_USE_NEW_BUILD_IMAGE = "true"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200